spring:
  application:
    name: Journal App
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}
      database: ${MONGO_DATABASE}
      auto-index-creation: true
  main:
    allow-circular-references: true
server:
  port: 8080

external:
  api:
    key: ${WEATHER_API_KEY}